#!/usr/bin/env bash

DIR="${HOME}/.tux-server"

if [ -d "${DIR}" ]; then
  cd "${DIR}" || exit 1
  notify-send "runing the app" && "${HOME}"/.cargo/bin/cargo run --release
else
  notify-send "building tux server" && git clone https://github.com/taishingi/tux.git "${DIR}" && cd "${DIR}" || exit 1
  "${HOME}"/.cargo/bin/cargo build --release || exit 1
  notify-send "running application"
  "${HOME}"/.cargo/bin/cargo run --release
fi
