#!/usr/bin/env bash

if [ -d /usr/local/bin/tux-server ];then
    cd /usr/local/bin/tux-server &&  /home/"${1}"/.cargo/bin/cargo run || exit 1
else
  git clone https://github.com/taishingi/tux.git /usr/local/bin/tux-server && cd /usr/local/bin/tux-server || exit 1
  /home/"${1}"/.cargo/bin/cargo run
fi
