#!/usr/bin/env bash

DIR="${HOME}/.tux-server"

if [ -d "${DIR}" ];then
    cd "${DIR}" && "${HOME}"/.cargo/bin/cargo run
else
  git clone https://github.com/taishingi/tux.git "${DIR}" && cd "${DIR}" || exit 1
 "${HOME}"/.cargo/bin/cargo run
fi
